if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }/*FB_PKG_DELIM*/

__d("ProfileCometMentionsFeedQuery_facebookRelayOperation",[],function(a,b,c,d,e,f){e.exports="5201052803333861"},null,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("ProfileCometMentionsFeedQuery$Parameters",["FBReelsEnableDefer.relayprovider","ProfileCometMentionsFeedQuery_facebookRelayOperation"],function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometMentionsFeedQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometMentionsFeedQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__FBReelsEnableDeferrelayprovider:b("FBReelsEnableDefer.relayprovider")}}};e.exports=a},null,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("ProfileCometMentionsTabWithDeepDiveRootQuery_facebookRelayOperation",[],function(a,b,c,d,e,f){e.exports="4870566943044056"},null,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("ProfileCometMentionsTabWithDeepDiveRootQuery$Parameters",["ProfileCometMentionsTabWithDeepDiveRootQuery_facebookRelayOperation"],function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometMentionsTabWithDeepDiveRootQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometMentionsTabWithDeepDiveRootQuery",operationKind:"query",text:null}};e.exports=a},null,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("ProfileCometReviewsFeedQuery_facebookRelayOperation",[],function(a,b,c,d,e,f){e.exports="5859479290769024"},null,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("ProfileCometReviewsFeedQuery$Parameters",["FBReelsEnableDefer.relayprovider","ProfileCometReviewsFeedQuery_facebookRelayOperation"],function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometReviewsFeedQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometReviewsFeedQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__FBReelsEnableDeferrelayprovider:b("FBReelsEnableDefer.relayprovider")}}};e.exports=a},null,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("ProfileCometReviewsTabRootQuery_facebookRelayOperation",[],function(a,b,c,d,e,f){e.exports="4848215338589877"},null,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("ProfileCometReviewsTabRootQuery$Parameters",["ProfileCometReviewsTabRootQuery_facebookRelayOperation"],function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("ProfileCometReviewsTabRootQuery_facebookRelayOperation"),metadata:{},name:"ProfileCometReviewsTabRootQuery",operationKind:"query",text:null}};e.exports=a},null,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("CometProfilePlusVideosRootQuery_facebookRelayOperation",[],function(a,b,c,d,e,f){e.exports="5687560837989546"},null,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("CometProfilePlusVideosRootQuery$Parameters",["CometProfilePlusVideosRootQuery_facebookRelayOperation"],function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometProfilePlusVideosRootQuery_facebookRelayOperation"),metadata:{},name:"CometProfilePlusVideosRootQuery",operationKind:"query",text:null}};e.exports=a},null,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("NullStateFiles",["cr:2972"],function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:2972")},98,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("NullStateFilesFB",["IconSource"],function(a,b,c,d,e,f,g){"use strict";a={dark:new(c("IconSource"))("nullStateGlyphs","/images/comet/empty_states_icons/files/null_states_files_dark_mode.svg",112),"default":new(c("IconSource"))("nullStateGlyphs","/images/comet/empty_states_icons/files/null_states_files_gray_wash.svg",112)};g["default"]=a},98,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("ProfileCometMentionsTabWithDeepDiveRouteRoot.entrypoint",["JSResourceForInteraction","ProfileCometMentionsFeedQuery$Parameters","ProfileCometMentionsTabWithDeepDiveRootQuery$Parameters","WebPixelRatio","buildCometProfileRoute.entrypoint"],function(a,b,c,d,e,f,g){"use strict";a=c("buildCometProfileRoute.entrypoint")(c("JSResourceForInteraction")("ProfileCometMentionsTabWithDeepDiveRoot.react").__setRef("ProfileCometMentionsTabWithDeepDiveRouteRoot.entrypoint"),function(a){a=a.routeProps;var b=a.userID;a=a.viewerID;return{queries:{mentionsFeedQueryReference:{environmentProviderOptions:{ssrBoundary:"root"},parameters:c("ProfileCometMentionsFeedQuery$Parameters"),variables:{UFI2CommentsProvider_commentsKey:"ProfileCometMentionsTabRoute",feedbackSource:0,feedLocation:"TIMELINE",privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"timeline",scale:d("WebPixelRatio").get(),sortBy:"MOST_RELEVANT",userID:String(b)||""}},mentionsTabRootQueryReference:{environmentProviderOptions:{ssrBoundary:"root"},parameters:c("ProfileCometMentionsTabWithDeepDiveRootQuery$Parameters"),variables:{isViewingSelf:b===a,scale:d("WebPixelRatio").get(),userID:String(b)||""}}}}});g["default"]=a},98,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("ProfileCometReviewsTabRouteRoot.entrypoint",["JSResourceForInteraction","ProfileCometReviewsFeedQuery$Parameters","ProfileCometReviewsTabRootQuery$Parameters","WebPixelRatio","buildCometProfileRoute.entrypoint"],function(a,b,c,d,e,f,g){"use strict";a=c("buildCometProfileRoute.entrypoint")(c("JSResourceForInteraction")("ProfileCometReviewsTabRoot.react").__setRef("ProfileCometReviewsTabRouteRoot.entrypoint"),function(a){a=a.routeProps.userID;return{queries:{reviewsFeedQueryReference:{environmentProviderOptions:{ssrBoundary:"root"},parameters:c("ProfileCometReviewsFeedQuery$Parameters"),variables:{UFI2CommentsProvider_commentsKey:"ProfileCometReviewsTabRoute",feedbackSource:0,feedLocation:"PAGE_SURFACE_RECOMMENDATIONS",privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"timeline",scale:d("WebPixelRatio").get(),userID:String(a)||""}},reviewsTabRootQueryReference:{environmentProviderOptions:{ssrBoundary:"root"},parameters:c("ProfileCometReviewsTabRootQuery$Parameters"),variables:{userID:String(a)||""}}}}});g["default"]=a},98,typeof self!=="undefined"&&self.document&&self.document.currentScript);
__d("CometProfilePlusVideosRoot.entrypoint",["CometProfilePlusVideosRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio","buildCometProfileRoute.entrypoint"],function(a,b,c,d,e,f,g){"use strict";a=c("buildCometProfileRoute.entrypoint")(c("JSResourceForInteraction")("CometProfilePlusVideosRoot.react").__setRef("CometProfilePlusVideosRoot.entrypoint"),function(a){var c;a=a.routeProps;var e=a.canViewerEditPage,f=a.isViewerCoreAppAdminNotLoggedIn,g=a.pageID;a=a.viewerID;return{extraProps:{canViewerEditPage:e,isViewerCoreAppAdminNotLoggedIn:f,pageID:(c=g)!=null?c:""},queries:{CometProfilePlusVideosRootQueryReference:{environmentProviderOptions:{actorID:a},parameters:b("CometProfilePlusVideosRootQuery$Parameters"),variables:{UFI2CommentsProvider_commentsKey:"CometProfilePlusVideosRoot",displayCommentsContextEnableComment:null,displayCommentsContextIsAdPreview:null,displayCommentsContextIsAggregatedShare:null,displayCommentsContextIsStorySet:null,displayCommentsFeedbackContext:null,feedbackSource:86,feedLocation:"PROFILE_PLUS_TIMELINE",focusCommentID:null,pageID:g,scale:d("WebPixelRatio").get()*4,shouldLoadAdminControls:e||f,showReactions:!0,useDefaultActor:!1}}}}});g["default"]=a},98,typeof self!=="undefined"&&self.document&&self.document.currentScript);